# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from doccontext.proto_gen import doccontext_pb2 as doccontext__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in doccontext_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocContextStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexDocument = channel.unary_unary(
                '/doccontext.v1.DocContext/IndexDocument',
                request_serializer=doccontext__pb2.IndexDocumentRequest.SerializeToString,
                response_deserializer=doccontext__pb2.IndexDocumentResponse.FromString,
                _registered_method=True)
        self.GetIndexingJobStatus = channel.unary_unary(
                '/doccontext.v1.DocContext/GetIndexingJobStatus',
                request_serializer=doccontext__pb2.GetIndexingJobStatusRequest.SerializeToString,
                response_deserializer=doccontext__pb2.GetIndexingJobStatusResponse.FromString,
                _registered_method=True)
        self.QueryDocuments = channel.unary_unary(
                '/doccontext.v1.DocContext/QueryDocuments',
                request_serializer=doccontext__pb2.QueryDocumentsRequest.SerializeToString,
                response_deserializer=doccontext__pb2.QueryDocumentsResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/doccontext.v1.DocContext/DeleteDocument',
                request_serializer=doccontext__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=doccontext__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)


class DocContextServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def IndexDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexingJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocContextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexDocument,
                    request_deserializer=doccontext__pb2.IndexDocumentRequest.FromString,
                    response_serializer=doccontext__pb2.IndexDocumentResponse.SerializeToString,
            ),
            'GetIndexingJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexingJobStatus,
                    request_deserializer=doccontext__pb2.GetIndexingJobStatusRequest.FromString,
                    response_serializer=doccontext__pb2.GetIndexingJobStatusResponse.SerializeToString,
            ),
            'QueryDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDocuments,
                    request_deserializer=doccontext__pb2.QueryDocumentsRequest.FromString,
                    response_serializer=doccontext__pb2.QueryDocumentsResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=doccontext__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=doccontext__pb2.DeleteDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doccontext.v1.DocContext', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doccontext.v1.DocContext', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocContext(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def IndexDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doccontext.v1.DocContext/IndexDocument',
            doccontext__pb2.IndexDocumentRequest.SerializeToString,
            doccontext__pb2.IndexDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexingJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doccontext.v1.DocContext/GetIndexingJobStatus',
            doccontext__pb2.GetIndexingJobStatusRequest.SerializeToString,
            doccontext__pb2.GetIndexingJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doccontext.v1.DocContext/QueryDocuments',
            doccontext__pb2.QueryDocumentsRequest.SerializeToString,
            doccontext__pb2.QueryDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doccontext.v1.DocContext/DeleteDocument',
            doccontext__pb2.DeleteDocumentRequest.SerializeToString,
            doccontext__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
